services:
  - type: web
    name: airq-riyadh
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATA_PATH
        value: data/riyadh_air_quality.csv
      - key: MODEL_PATH
        value: models/riyadh_pm25_xgb.joblib
      - key: TARGET
        value: PM2.5
    healthCheckPath: /health
    autoDeploy: true
